
tasks_meps = [
    {
        "name": "MEPS: Expenditure by Age Group, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["expenditure", "age_group"],
        "mode": "sample",
        "wgh_col": "weight",
        "prompt": "What is the annual healthcare expenditure for a person aged {} in the US? Answer with a number (in US dollars).",
        "levels": None,
    },
    {
        "name": "MEPS: Office-based Visits by Age Group, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["office_visits", "age_group"],
        "mode": "sample",
        "wgh_col": "weight",
        "prompt": "How many office-based medical visits does a person aged {} have per year? Answer with a number.",
        "levels": None,
    },
    {
        "name": "MEPS: Inpatient Visits by Age Group, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["inpatient_visits", "age_group"],
        "mode": "sample",
        "wgh_col": "weight",
        "prompt": "How many inpatient hospital visits does a person aged {} have per year? Answer with a number.",
        "levels": None,
    },
    {
        "name": "MEPS: Dental Visits by Age Group, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["dental_visits", "age_group"],
        "mode": "sample",
        "wgh_col": "weight",
        "prompt": "How many dental visits does a person aged {} have per year? Answer with a number.",
        "levels": None,
    },
    {
        "name": "MEPS: Has Insurance by Age Group, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["insured", "age_group"],
        "mode": "logits",
        "wgh_col": "weight",
        "prompt": "Does a person aged {} have any health insurance? Answer yes or no.",
        "levels": [["No", "no"], ["Yes", "yes"]],
    },
    {
        "name": "MEPS: Expenditure by Race, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["expenditure", "race"],
        "mode": "sample",
        "wgh_col": "weight",
        "prompt": "What is the annual healthcare expenditure for a {} person in the US? Answer with a number (in US dollars).",
        "levels": None,
    },
    {
        "name": "MEPS: Office-based Visits by Race, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["office_visits", "race"],
        "mode": "sample",
        "wgh_col": "weight",
        "prompt": "How many office-based medical visits does a {} person have per year? Answer with a number.",
        "levels": None,
    },
    {
        "name": "MEPS: Inpatient Visits by Race, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["inpatient_visits", "race"],
        "mode": "sample",
        "wgh_col": "weight",
        "prompt": "How many inpatient hospital visits does a {} person have per year? Answer with a number.",
        "levels": None,
    },
    {
        "name": "MEPS: Dental Visits by Race, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["dental_visits", "race"],
        "mode": "sample",
        "wgh_col": "weight",
        "prompt": "How many dental visits does a {} person have per year? Answer with a number.",
        "levels": None,
    },
    {
        "name": "MEPS: Has Insurance by Race, Q&A",
        "dataset": "data/clean/meps.parquet",
        "variables": ["insured", "race"],
        "mode": "logits",
        "wgh_col": "weight",
        "prompt": "Does a {} person have any health insurance? Answer yes or no.",
        "levels": [["No", "no"], ["Yes", "yes"]],
    },
]
